name: Release

on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-18.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      USE_CCACHE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Android build
        uses: ./.github/actions/build-android
        with:
          node-version: '12.x'
          java-version: '11'

  ios:
    runs-on: macos-11
    name: iOS
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      USE_CCACHE: 1
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: iOS build
        uses: ./.github/actions/build-ios
        with:
          node-version: '12.x'

  package:
    runs-on: macos-11
    name: Package
    environment: Release
    env:
      SDK_BUILD_CACHE_DIR: ${{ github.workspace }}/.native-modules
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    needs: [android, ios]
    steps:
    - uses: actions/checkout@v2
    - name: Create version tag
      run: |
        PACKAGE_VERSION=$(sed -n 's/^ *"version": *"//p' package.json | tr -d '"' | tr -d ',' | tr -d '[[:space:]]')
        VTAG="${PACKAGE_VERSION}.v${GA}"
        echo "vtag=${VTAG}" >> $GITHUB_ENV
    - name: Package
      uses: ./.github/actions/build-package
      with:
        node-version: '12.x'
        java-version: '11'
        vtag: ${{ env.vtag }}
